<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pinnwand"
 *
 * Auto generated by Extension Builder 2018-07-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Pinnwand',
    'description' => 'Simple system to pin small snippets on a page.',
    'category' => 'plugin',
    'author' => 'Jan Schrewe',
    'author_email' => 'jan.schrewe@uni-goettingen.de',
    'state' => 'beta',
    'uploadfolder' => 1,
    'createDirs' => '',
    'clearCacheOnLoad' => 1,
    'version' => '0.9.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
