<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "dud_pinnwand"
 *
 * Auto generated by Extension Builder 2014-04-11
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'd&d Pinnwand',
	'description' => 'Displays cropped linked images for right column',
	'category' => 'plugin',
	'author' => 'Tom Lachemund',
	'author_email' => 'support@d-welt.de',
	'author_company' => 'd&d design & distribution GmbH & Co. KG',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '8.7.1',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.2',
			'fluid' => '6.2',
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>