<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "dud_pinnwand"
 *
 * Auto generated by Extension Builder 2014-04-11
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
    'title' => 'Pinnwand',
    'description' => 'Displays text snippets and images',
    'category' => 'plugin',
    'author' => 'Jan Schrewe/Tom Lachemund',
    'author_email' => 'jan.schrewe@uni-goettingen.de',
    'author_company' => 'Kooperationsstelle Hochschulen und Gewerkschften Göttingen',
    'shy' => '',
    'priority' => '',
    'module' => '',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'modify_tables' => '',
    'clearCacheOnLoad' => 0,
    'lockType' => '',
    'version' => '1.0',
    'constraints' => array(
        'depends' => array(
            'extbase' => '6.2',
            'fluid' => '6.2',
            'typo3' => '6.2',
        ),
        'conflicts' => array(
        ),
        'suggests' => array(
        ),
    ),
);
